model = "gpt-5.4"
approval_policy = "never"
personality = "pragmatic"
model_reasoning_effort = "medium"
approvals_reviewer = "user"

[notice]
hide_full_access_warning = true
hide_rate_limit_model_nudge = true

[notice.model_migrations]
"gpt-5.2" = "gpt-5.2-codex"
"gpt-5.1-codex-max" = "gpt-5.2-codex"
gpt-5-codex = "gpt-5.2-codex"
"gpt-5.3-codex" = "gpt-5.4"

[features]
unified_exec = true
shell_snapshot = true
#experimental_windows_sandbox = true
tui2 = false
steer = true
#powershell_utf8 = true
multi_agent = true

[tui]
notifications = true
animations = false

[sandbox_workspace_write]
network_access = true
hide_agent_reasoning = true
show_raw_agent_reasoning = false

